/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PrivateUserRouteImport } from './routes/_private/user'
import { Route as PrivateProcessesRouteImport } from './routes/_private/processes'
import { Route as PrivateDocumentsRouteImport } from './routes/_private/documents'
import { Route as PrivateDiagramsRouteImport } from './routes/_private/diagrams'
import { Route as PrivateDashboardRouteImport } from './routes/_private/dashboard'
import { Route as PrivateFlowsIndexRouteImport } from './routes/_private/flows/index'
import { Route as PrivateFlowsIdIndexRouteImport } from './routes/_private/flows/$id/index'
import { Route as PrivateFlowsIdEditorRouteImport } from './routes/_private/flows/$id/editor'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PrivateUserRoute = PrivateUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateProcessesRoute = PrivateProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateDocumentsRoute = PrivateDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateDiagramsRoute = PrivateDiagramsRouteImport.update({
  id: '/diagrams',
  path: '/diagrams',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateDashboardRoute = PrivateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateFlowsIndexRoute = PrivateFlowsIndexRouteImport.update({
  id: '/flows/',
  path: '/flows/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateFlowsIdIndexRoute = PrivateFlowsIdIndexRouteImport.update({
  id: '/flows/$id/',
  path: '/flows/$id/',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateFlowsIdEditorRoute = PrivateFlowsIdEditorRouteImport.update({
  id: '/flows/$id/editor',
  path: '/flows/$id/editor',
  getParentRoute: () => PrivateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof PrivateDashboardRoute
  '/diagrams': typeof PrivateDiagramsRoute
  '/documents': typeof PrivateDocumentsRoute
  '/processes': typeof PrivateProcessesRoute
  '/user': typeof PrivateUserRoute
  '/login': typeof PublicLoginRoute
  '/': typeof PublicIndexRoute
  '/flows': typeof PrivateFlowsIndexRoute
  '/flows/$id/editor': typeof PrivateFlowsIdEditorRoute
  '/flows/$id': typeof PrivateFlowsIdIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof PrivateDashboardRoute
  '/diagrams': typeof PrivateDiagramsRoute
  '/documents': typeof PrivateDocumentsRoute
  '/processes': typeof PrivateProcessesRoute
  '/user': typeof PrivateUserRoute
  '/login': typeof PublicLoginRoute
  '/': typeof PublicIndexRoute
  '/flows': typeof PrivateFlowsIndexRoute
  '/flows/$id/editor': typeof PrivateFlowsIdEditorRoute
  '/flows/$id': typeof PrivateFlowsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_private/dashboard': typeof PrivateDashboardRoute
  '/_private/diagrams': typeof PrivateDiagramsRoute
  '/_private/documents': typeof PrivateDocumentsRoute
  '/_private/processes': typeof PrivateProcessesRoute
  '/_private/user': typeof PrivateUserRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/': typeof PublicIndexRoute
  '/_private/flows/': typeof PrivateFlowsIndexRoute
  '/_private/flows/$id/editor': typeof PrivateFlowsIdEditorRoute
  '/_private/flows/$id/': typeof PrivateFlowsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/diagrams'
    | '/documents'
    | '/processes'
    | '/user'
    | '/login'
    | '/'
    | '/flows'
    | '/flows/$id/editor'
    | '/flows/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/diagrams'
    | '/documents'
    | '/processes'
    | '/user'
    | '/login'
    | '/'
    | '/flows'
    | '/flows/$id/editor'
    | '/flows/$id'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/dashboard'
    | '/_private/diagrams'
    | '/_private/documents'
    | '/_private/processes'
    | '/_private/user'
    | '/_public/login'
    | '/_public/'
    | '/_private/flows/'
    | '/_private/flows/$id/editor'
    | '/_private/flows/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_private/user': {
      id: '/_private/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof PrivateUserRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/processes': {
      id: '/_private/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof PrivateProcessesRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/documents': {
      id: '/_private/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof PrivateDocumentsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/diagrams': {
      id: '/_private/diagrams'
      path: '/diagrams'
      fullPath: '/diagrams'
      preLoaderRoute: typeof PrivateDiagramsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/flows/': {
      id: '/_private/flows/'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof PrivateFlowsIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/flows/$id/': {
      id: '/_private/flows/$id/'
      path: '/flows/$id'
      fullPath: '/flows/$id'
      preLoaderRoute: typeof PrivateFlowsIdIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/flows/$id/editor': {
      id: '/_private/flows/$id/editor'
      path: '/flows/$id/editor'
      fullPath: '/flows/$id/editor'
      preLoaderRoute: typeof PrivateFlowsIdEditorRouteImport
      parentRoute: typeof PrivateRoute
    }
  }
}

interface PrivateRouteChildren {
  PrivateDashboardRoute: typeof PrivateDashboardRoute
  PrivateDiagramsRoute: typeof PrivateDiagramsRoute
  PrivateDocumentsRoute: typeof PrivateDocumentsRoute
  PrivateProcessesRoute: typeof PrivateProcessesRoute
  PrivateUserRoute: typeof PrivateUserRoute
  PrivateFlowsIndexRoute: typeof PrivateFlowsIndexRoute
  PrivateFlowsIdEditorRoute: typeof PrivateFlowsIdEditorRoute
  PrivateFlowsIdIndexRoute: typeof PrivateFlowsIdIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateDashboardRoute: PrivateDashboardRoute,
  PrivateDiagramsRoute: PrivateDiagramsRoute,
  PrivateDocumentsRoute: PrivateDocumentsRoute,
  PrivateProcessesRoute: PrivateProcessesRoute,
  PrivateUserRoute: PrivateUserRoute,
  PrivateFlowsIndexRoute: PrivateFlowsIndexRoute,
  PrivateFlowsIdEditorRoute: PrivateFlowsIdEditorRoute,
  PrivateFlowsIdIndexRoute: PrivateFlowsIdIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
